### ISSUE TITLE
openfl.net.Signal<String> cannot be called

### ISSUE THREAD

**Issue by anhduongxanh63** [soywiz/openfl-websocket#6]
Hi soywiz,
I tested your lib but I get error:
openfl.net.Signal<String> cannot be called.
Maybe in Websocket.hx cannot detect class Signal in package openfl.net.Signal.
Please check it, thank you :)

**Comment by soywiz** [comment]
It is openfl.net.Websocket.Signal (since it is an inner class). Where are you getting that error?

**Comment by anhduongxanh63** [comment]
Sorry, maybe it's human error of mine, thank you :D
